### ISSUE TITLE
ModuleNotFoundError: No module named 'bark.config.consumer'

### ISSUE THREAD

**Issue by andrianowinatra** [jfm/bark#10]
I think there are uncommitted files to the project. I'm unable to run the project at all.

```
Traceback (most recent call last):
  File "Bark.py", line 9, in <module>
    from bark.config.consumer import BarkConsumer
ModuleNotFoundError: No module named 'bark.config.consumer'
```

**Comment by jfm** [comment]
Ah yes, there is I need to figure out how to get around that... The problem is that I don't want to distribute the consumer key/secret on github. The idea was to do the same as rainbowstream does and only distribute it in the release packages. But I might have made a mistake in the implementation

**Comment by andrianowinatra** [comment]
I think environment variables or env files might be a good idea as well for this

**Comment by jfm** [comment]
It will read the keys/secrets from the config file if they are there (at least that is the idea). But for general release we don't want to require all users to register themselves as developers :) So they should only have to get their access key/secrets by doing the pin based authentication.

**Comment by andrianowinatra** [comment]
Is this config file format documented anywhere? 💡

**Comment by jfm** [comment]
Create a file called bark.conf and add the following:
I'll push an example as soon as I have time (hopefully tonight)

You will have to fill out the consumer and access token values though

[CONFIGURATION]
simulate_tweeting = true

[LOGGING]
logfile: bark.log
loglevel: debug

[API]
consumer_key:
consumer_secret:
access_token: 
access_token_secret:
